apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  namespace: opportal-pro-ingress
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-portal-pro
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 30000
  - name: https
    port: 443
    protocol: TCP
    nodePort: 30443



